### ISSUE TITLE
The recv_callback function has a typo problem

### ISSUE THREAD

**Issue by chenhuimao** [tony-go/snixpc#4]
locl.release() should be changed to lock.release()
https://github.com/tony-go/snixpc/blob/aa684975a8b264b5ccb07d6248e6c55e98ad399d/snif.py#L174

**Comment by tony-go** [comment]
Hey @chenhuimao :) 

Thanks for reporting this! 

I'll take care of this :)

**Comment by tony-go** [comment]
Hey @chenhuimao 

has been fixed in https://github.com/tony-go/snixpc/pull/5
